spring.application.name=backend
spring.config.import=optional:file:.env[.properties]
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
server.port=${SERVER_PORT:8081}
catalyst.base-url=${CATALYST_BASE_URL:https://catalyst-backend-d4eu.onrender.com/api}
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=60MB
rrl.max-file-size-mb=20
